.PHONY: clean All

All:
	@echo "----------Building project:[ PEC_2 - Debug ]----------"
	@cd "PEC_2" && "$(MAKE)" -f  "PEC_2.mk"
clean:
	@echo "----------Cleaning project:[ PEC_2 - Debug ]----------"
	@cd "PEC_2" && "$(MAKE)" -f  "PEC_2.mk" clean
